import {
  calculateNextExecutionDate,
  isAfterEndDate,
  isDue,
  toUtcDateOnly,
} from "../../lib/recurrence.js";
import {
  Prisma,
  type PrismaClient,
  type RecurringTransaction,
} from "../../generated/prisma/client.js";

/**
 * Safety bound on how many occurrences a single template may generate in one
 * run. A template dormant for years (or a scheduler that stopped running)
 * would otherwise emit an unbounded backlog in a single pass. 366 covers a
 * full year of DAILY catch-up; anything beyond that is carried to the next run
 * rather than dropped, since `nextExecutionDate` keeps advancing.
 */
export const MAX_CATCH_UP_ITERATIONS = 366;

/** Per-run counters, shaped for a scheduler's logs and monitoring. */
export interface ProcessingSummary {
  /** Templates examined (claimed as due) in this run. */
  processed: number;
  /** Transactions actually written. */
  generated: number;
  /** Occurrences deliberately not written: archived account/category, or an
   *  occurrence a previous run had already generated (idempotency hit). */
  skipped: number;
  /** Templates abandoned mid-run because of an unexpected error. The run
   *  continues: one bad template must not stop the rest. */
  failed: number;
}

/**
 * Scheduler-agnostic entry point. Cron, Railway, a queue worker or a test can
 * drive the engine through this interface without the domain knowing which.
 */
export interface RecurringTransactionProcessor {
  processDueRecurringTransactions(asOf?: Date): Promise<ProcessingSummary>;
}

interface OccurrenceOutcome {
  generated: number;
  skipped: number;
}

/**
 * Writes the occurrence for `date`, unless it must be skipped.
 *
 * Idempotency has two layers: this insert races against the unique index on
 * (recurringTransactionId, date), so even two schedulers running concurrently
 * cannot produce a duplicate — the loser gets P2002 and counts as skipped.
 */
async function generateOccurrence(
  prisma: PrismaClient,
  template: RecurringTransaction,
  date: Date,
): Promise<"generated" | "skipped"> {
  // Re-read per occurrence: an account or category archived after the template
  // was created must not receive new movements (business rule 4). The schedule
  // still advances, so the template resumes cleanly once it is unarchived.
  const [account, category] = await Promise.all([
    prisma.account.findUnique({ where: { id: template.accountId } }),
    prisma.category.findUnique({ where: { id: template.categoryId } }),
  ]);

  if (!account || account.archivedAt || !category || category.archivedAt) {
    return "skipped";
  }

  try {
    await prisma.transaction.create({
      data: {
        accountId: template.accountId,
        categoryId: template.categoryId,
        recurringTransactionId: template.id,
        amount: template.amount,
        currency: template.currency,
        // Type is derived, never stored on the template (business rule 2).
        type: category.type,
        date,
      },
    });
    return "generated";
  } catch (error) {
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") {
      // Already generated by a previous (or concurrent) run.
      return "skipped";
    }
    throw error;
  }
}

/**
 * Advances one template to its next pending occurrence, generating everything
 * due up to `asOf`.
 */
async function processTemplate(
  prisma: PrismaClient,
  template: RecurringTransaction,
  asOf: Date,
): Promise<OccurrenceOutcome> {
  const outcome: OccurrenceOutcome = { generated: 0, skipped: 0 };
  let cursor = toUtcDateOnly(template.nextExecutionDate);
  let iterations = 0;

  while (isDue(cursor, asOf) && !isAfterEndDate(cursor, template.endDate)) {
    if (iterations >= MAX_CATCH_UP_ITERATIONS) {
      break;
    }
    iterations += 1;

    const result = await generateOccurrence(prisma, template, cursor);
    outcome[result] += 1;

    const following = calculateNextExecutionDate(cursor, template.frequency, template.startDate);
    // Persist after every occurrence rather than once at the end: a crash
    // mid-catch-up must not replay the occurrences already written.
    await prisma.recurringTransaction.update({
      where: { id: template.id },
      data: { nextExecutionDate: following },
    });
    cursor = following;
  }

  return outcome;
}

export function createRecurringTransactionProcessor(
  prisma: PrismaClient,
): RecurringTransactionProcessor {
  return {
    async processDueRecurringTransactions(asOf: Date = new Date()): Promise<ProcessingSummary> {
      const today = toUtcDateOnly(asOf);
      const summary: ProcessingSummary = { processed: 0, generated: 0, skipped: 0, failed: 0 };

      const due = await prisma.recurringTransaction.findMany({
        where: { isActive: true, nextExecutionDate: { lte: today } },
      });

      for (const template of due) {
        summary.processed += 1;
        try {
          const outcome = await processTemplate(prisma, template, today);
          summary.generated += outcome.generated;
          summary.skipped += outcome.skipped;
        } catch {
          // One malformed or conflicting template must not abort the batch;
          // its `nextExecutionDate` is unchanged, so the next run retries it.
          summary.failed += 1;
        }
      }

      return summary;
    },
  };
}
